"""Memory store operations for ACT-R memory plugin."""

import logging
from typing import Any, cast

from ananta.core.domain.enums import ActionStatus
from ananta.error_handling import FrameworkError
from ananta.services.memory_service.actr.constants import VECTOR_NAMESPACE
from ananta.services.memory_service.schema import NAMESPACE

from .record_helpers import (
    extract_generated_id,
    parse_memory_json_fields,
    serialize_memory_for_storage,
)

logger = logging.getLogger(__name__)


def get_memory(state_service: Any, memory_id: str) -> dict[str, Any] | None:
    """Get a memory by ID from state service.

    Returns None when the memory does not exist. Memory deletes are HARD
    (actr hard-delete slice, 2026-06-21), so a deleted memory's row is
    physically gone — no ``is_deleted=0`` filter is needed, and orphan-vector
    cleanup keys off this returning None for an absent row.
    """
    result = state_service.read_state(
        namespace=NAMESPACE,
        query={"table": "memory", "filters": {"id": memory_id}},
    )
    rows = result.get("data", {}).get("records", [])
    if not rows:
        return None

    memory = rows[0]
    parse_memory_json_fields(memory)
    return cast(dict[str, Any], memory)


def save_memory(state_service: Any, memory: dict[str, Any]) -> str:
    """Save a memory to state service. Returns the memory ID."""
    record = serialize_memory_for_storage(memory)
    result = persist_memory_record(state_service, record)

    if result.get("action_status") != ActionStatus.COMPLETED.value:
        error_msg = result.get("error", "Unknown error saving memory")
        raise FrameworkError(
            message=f"Failed to save memory: {error_msg}",
            error_code="memory.storage_error",
        )

    return extract_generated_id(result, record)


def persist_memory_record(state_service: Any, record: dict[str, Any]) -> dict[str, Any]:
    """Persist memory record using appropriate method."""
    if "id" in record and record.get("id"):
        result: dict[str, Any] = state_service.upsert_state(
            namespace=NAMESPACE,
            data={"table": "memory", "record": record, "conflict_columns": ["id"]},
        )
        return result
    write_result: dict[str, Any] = state_service.write_state(
        namespace=NAMESPACE,
        data={"table": "memory", "record": record},
    )
    return write_result


def get_memorization(state_service: Any, memory_id: str) -> dict[str, Any] | None:
    """Get a memorization record by memory ID."""
    result = state_service.read_state(
        namespace=NAMESPACE,
        query={
            "table": "memorization",
            "filters": {"actr_memory_plugin__memory_id": memory_id},
        },
    )
    rows = result.get("data", {}).get("records", [])
    if not rows:
        return None

    return cast(dict[str, Any], rows[0])


def save_memorization(state_service: Any, record: dict[str, Any]) -> str:
    """Save a memorization record. Returns the record ID.

    Memorization records always have an ID (generated by caller), so uses
    upsert_state for insert-or-update semantics.
    """
    save_record = dict(record)
    if "memory_id" in save_record:
        save_record["actr_memory_plugin__memory_id"] = save_record.pop("memory_id")

    result = state_service.upsert_state(
        namespace=NAMESPACE,
        data={"table": "memorization", "record": save_record, "conflict_columns": ["id"]},
    )

    if result.get("action_status") != ActionStatus.COMPLETED.value:
        error_msg = result.get("error", "Unknown error saving memorization")
        raise FrameworkError(
            message=f"Failed to save memorization: {error_msg}",
            error_code="memory.storage_error",
        )

    data = result.get("data", {})
    if isinstance(data, dict):
        result_data = data.get("result", {})
        if isinstance(result_data, dict):
            generated_id = result_data.get("generated_id")
            if isinstance(generated_id, str):
                return generated_id

    record_id = record.get("id", "")
    return str(record_id) if record_id else ""


def get_all_memories(
    state_service: Any,
    memory_type: str | None = None,
    status: str | None = None,
    tag: str | None = None,
) -> list[dict[str, Any]]:
    """Get all memories matching filters."""
    filters: dict[str, Any] = {}
    if memory_type:
        filters["memory_type"] = memory_type
    if status:
        filters["status"] = status

    result = state_service.read_state(
        namespace=NAMESPACE,
        query={"table": "memory", "filters": filters} if filters else {"table": "memory"},
    )

    rows = result.get("data", {}).get("records", [])

    memories: list[dict[str, Any]] = []
    for row in rows:
        if not isinstance(row, dict):
            continue

        parse_memory_json_fields(row)

        if tag and tag not in row.get("tags", []):
            continue

        memories.append(row)

    return memories


def find_memories_by_tag(state_service: Any, tag: str) -> list[dict[str, Any]]:
    """Find all memories with a specific tag (including archived)."""
    return get_all_memories(state_service, status=None, tag=tag)


def delete_memory_records(state_service: Any, memory_ids: list[str]) -> int:
    """Hard-delete memory records by ID. Returns count deleted.

    Memory deletes are HARD (actr hard-delete slice, 2026-06-21): the row is
    physically removed, not flagged ``is_deleted=1``. soft-delete was dropped
    for the actr memory tables because the main read paths (get_all_memories,
    build_recall_filters) never filtered ``is_deleted``, so soft-deletes never
    actually hid anything.
    """
    deleted = 0
    for memory_id in memory_ids:
        state_service.delete_records(
            namespace=NAMESPACE,
            query={"table": "memory", "filters": {"id": memory_id}, "soft_delete": False},
        )
        deleted += 1
    return deleted


def get_all_memorizations(
    state_service: Any,
    status: str | None = None,
) -> list[dict[str, Any]]:
    """Get all memorization records matching filters."""
    filters: dict[str, Any] = {}
    if status:
        filters["status"] = status

    result = state_service.read_state(
        namespace=NAMESPACE,
        query={"table": "memorization", "filters": filters}
        if filters
        else {"table": "memorization"},
    )

    rows = result.get("data", {}).get("records", [])

    records: list[dict[str, Any]] = []
    for row in rows:
        if not isinstance(row, dict):
            continue

        if "actr_memory_plugin__memory_id" in row:
            row["memory_id"] = row.pop("actr_memory_plugin__memory_id")

        records.append(row)

    return records


def store_memory_vector(
    vector_service: Any,
    memory_id: str,
    embedding: list[float],
    now_iso: str,
    tags: list[str] | None = None,
) -> None:
    """Store memory vector. Raises FrameworkError on failure."""
    if vector_service is None:
        raise FrameworkError(
            message="Vector service not available",
            error_code="memory.vector_unavailable",
        )

    metadata: dict[str, Any] = {
        "memory_type": "episodic",
        "status": "active",
        "created_at": now_iso,
    }
    if tags:
        metadata["tags"] = tags

    result = vector_service.store_vectors(
        VECTOR_NAMESPACE,
        [
            {
                "external_id": memory_id,
                "vector": embedding,
                "dimension": len(embedding),
                "metadata": metadata,
            }
        ],
    )
    if isinstance(result, dict) and result.get("action_status") == ActionStatus.ERROR.value:
        error = result.get("error", {})
        error_msg = error.get("message", str(error)) if isinstance(error, dict) else str(error)
        raise FrameworkError(
            message=f"Vector service error: {error_msg}",
            error_code="memory.vector_error",
        )
