"""Factory for creating ScheduleData objects.

This module provides a stateless factory class for building and validating
schedule data objects. It extracts the schedule building logic from plugin.py
to provide a clean separation of concerns.
"""

import datetime
from typing import Any

from ..constants import SchedulerJobStatus
from ..models import ActionData, ScheduleData

RELOAD_SAFE = True


class ScheduleFactory:
    """Factory for creating and validating ScheduleData objects.

    This is a stateless factory that provides pure functions for building
    ScheduleData objects from various input formats. It handles:
    - Parameter extraction from action definitions
    - Schedule type-specific logic (recurring vs one-time)
    - Validation of schedule parameters
    - Building ScheduleData objects with proper defaults
    """

    @staticmethod
    def extract_params(params: dict[str, Any]) -> dict[str, Any]:
        """Extract parameters from action definition.

        Handles both direct parameter format and nested action format:
        - {"action": {"parameters": {...}}} -> extract parameters
        - {"parameters": {...}} -> extract parameters
        - {...} -> use params directly

        Args:
            params: Parameter dictionary from action invocation

        Returns:
            Extracted parameters dictionary
        """
        if isinstance(params, dict) and "action" in params:  # type: ignore[reportUnnecessaryIsInstance]
            action = params["action"]
            if isinstance(action, dict):
                result = action.get("parameters", {})
                return result if isinstance(result, dict) else {}
            return {}
        result = params.get("parameters", params)
        return result if isinstance(result, dict) else {}  # type: ignore[reportUnnecessaryIsInstance]

    @staticmethod
    def create_cron_schedule_data(
        cron_expression: str,
        label: str = "Untitled Schedule",
        tags: list[str] | None = None,
        actions: list[ActionData] | None = None,
        action_name: str = "",
        action_parameters: dict[str, Any] | None = None,
        session_id: str | None = None,
        flow_id: str | None = None,
    ) -> ScheduleData:
        """Create ScheduleData for a recurring (cron) schedule.

        Args:
            cron_expression: Cron expression defining the schedule
            label: Human-readable label for the schedule
            tags: Optional tags for schedule organization
            actions: List of actions to execute (new format)
            action_name: Legacy single action name
            action_parameters: Legacy single action parameters
            session_id: Session context for action execution
            flow_id: Flow context for action execution

        Returns:
            ScheduleData object configured for recurring execution
        """
        return ScheduleData(
            id=None,  # Will be auto-generated by StateService
            label=label,
            tags=tags or [],
            type="recurring",
            cron_expression=cron_expression,
            run_at=None,
            actions=actions or [],
            action_name=action_name,
            action_parameters=action_parameters or {},
            status=SchedulerJobStatus.SCHEDULED,
            session_id=session_id,
            flow_id=flow_id,
            error_message=None,
        )

    @staticmethod
    def create_one_time_schedule_data(
        run_at: datetime.datetime,
        label: str = "Untitled Schedule",
        tags: list[str] | None = None,
        actions: list[ActionData] | None = None,
        action_name: str = "",
        action_parameters: dict[str, Any] | None = None,
        session_id: str | None = None,
        flow_id: str | None = None,
    ) -> ScheduleData:
        """Create ScheduleData for a one-time (delayed) schedule.

        Args:
            run_at: When to execute the schedule
            label: Human-readable label for the schedule
            tags: Optional tags for schedule organization
            actions: List of actions to execute (new format)
            action_name: Legacy single action name
            action_parameters: Legacy single action parameters
            session_id: Session context for action execution
            flow_id: Flow context for action execution

        Returns:
            ScheduleData object configured for one-time execution
        """
        return ScheduleData(
            id=None,  # Will be auto-generated by StateService
            label=label,
            tags=tags or [],
            type="one_time",
            run_at=run_at.isoformat(),
            cron_expression=None,
            actions=actions or [],
            action_name=action_name,
            action_parameters=action_parameters or {},
            status=SchedulerJobStatus.SCHEDULED,
            session_id=session_id,
            flow_id=flow_id,
            error_message=None,
        )

    @staticmethod
    def _normalize_action_entry(action: dict[str, Any]) -> dict[str, Any]:
        """Normalize common action shapes (process_key/arguments) to ActionData schema."""
        normalized: dict[str, Any] = {}
        for key, value in action.items():
            normalized[key] = value

        if "name" not in normalized and "process_key" in normalized:
            normalized["name"] = normalized.pop("process_key")

        if "parameters" not in normalized:
            if "arguments" in normalized:
                normalized["parameters"] = normalized.pop("arguments")
            else:
                normalized["parameters"] = {}

        return normalized

    @staticmethod
    def _parse_new_format_actions(
        actions_data: Any,
    ) -> tuple[list[ActionData], str, dict[str, Any]]:
        if actions_data is None:
            actions_data = []
        if not isinstance(actions_data, list):
            raise ValueError("actions must be provided as a list")

        normalized_actions = []
        for action in actions_data:
            if not isinstance(action, dict):
                raise ValueError("Each action entry must be an object")
            normalized = ScheduleFactory._normalize_action_entry(action)
            if "name" not in normalized:
                raise ValueError("Each action must include a 'name' or 'process_key'")
            normalized_actions.append(normalized)

        actions_list = [ActionData(**action) for action in normalized_actions]
        legacy_action_name = normalized_actions[0].get("name", "") if normalized_actions else ""
        legacy_action_params = normalized_actions[0].get("parameters", {}) if normalized_actions else {}
        return actions_list, legacy_action_name, legacy_action_params

    @staticmethod
    def _parse_memory_tag_actions(
        memory_tag: str,
    ) -> tuple[list[ActionData], str, dict[str, Any]]:
        if not memory_tag.strip():
            raise ValueError("memory_tag must be a non-empty string")

        lookup_params: dict[str, Any] = {
            "tag": memory_tag.strip(),
            "include_archived": False,
        }
        legacy_action_name = "service_interface::memory_service::get_memories_by_tag"
        actions_list = [
            ActionData(
                name=legacy_action_name,
                parameters=lookup_params,
                result_processor=None,
                result_processor_kind=None,
            )
        ]
        return actions_list, legacy_action_name, lookup_params

    @staticmethod
    def parse_actions_from_params(
        params: dict[str, Any],
    ) -> tuple[list[ActionData], str, dict[str, Any]]:
        """Parse actions from parameters, supporting both legacy and new formats.

        Supports:
        - New format: {"actions": [{"name": "...", "parameters": {...}}, ...]}
        - Legacy format: {"action_name": "...", "action_parameters": {...}}

        Args:
            params: Extracted parameters dictionary

        Returns:
            Tuple of (actions_list, legacy_action_name, legacy_action_params)

        Raises:
            ValueError: If neither format is provided
        """
        if "actions" in params or "action_definitions" in params:
            return ScheduleFactory._parse_new_format_actions(
                params.get("actions") or params.get("action_definitions", [])
            )
        if "action_name" in params:
            legacy_action_name = params.get("action_name", "")
            legacy_action_params = params.get("action_parameters", {})
            actions_list = [
                ActionData(
                    name=legacy_action_name,
                    parameters=legacy_action_params,
                    result_processor=None,
                    result_processor_kind=None,
                )
            ]
            return actions_list, legacy_action_name, legacy_action_params
        if "memory_tag" in params:
            return ScheduleFactory._parse_memory_tag_actions(params["memory_tag"])
        raise ValueError(
            "Must provide 'actions', 'action_name', or 'memory_tag' parameter"
        )
